# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01433bf20245220bda651c50ec8a0dcf1abf29a9c65538c89278a0c8369e9c9bdcab5a52e12f8b91131aac3222eba14db8803d2b30ec7756a0de111417255a3a

test:
  secret_key_base: b585f927caf5e3a7bf7616bdcdd74deb1d623d74036f771a66153ae53cadb72c390a8e7403da1537ce4ed85b3f70d1e11b74fa1cd34aa531e0a79704cabea9f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
